### ISSUE TITLE
should handle enforce_https query param

### ISSUE THREAD

**Issue by rnons** [psibi/yesod-auth-fb#2]
Recently, facebook added `enforce_https=1` to the callback url `https://hostname/auth/page/fb/proceed?code=<code>&enforce_https=1`, `yesod-auth-fb` will throw an exception

I fixed it by

```diff
        let proceedUrl = render $ tm proceedR
-            query' = [(a,b) | (a, Just b) <- query]
+            query' = [(a,b) | (a, Just b) <- query, a == "code"]
        token <- liftSubHandler $ YF.runYesodFbT $ FB.getUserAccessTokenStep2 proceedUrl query'
```

It can be changed from `fb` side as well

```
getUserAccessTokenStep2 redirectUrl query =
  case query of
    [code@("code", _)] ->
```

I will let you decide

**Comment by psibi** [comment]
Can you point me to the documentation where facebook added to it ? Also, I would love to take a PR if possible.

**Comment by rnons** [comment]
https://developers.facebook.com/docs/facebook-login/changelog
https://github.com/facebook/php-graph-sdk/issues/1049

I can't find mention of `enforce_https` param from facebook documentation, I just observed it.

Will send a PR later today.

**Comment by psibi** [comment]
:+1:
